# Generated by Django 2.2.1 on 2021-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211108_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('PREFER NOT TO SAY', 'Prefer Not To Say')], default='Female', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(blank=True, choices=[('B.TECH', 'B.Tech'), ('IDD', 'IDD'), ('M.TECH', 'M.Tech'), ('PhD', 'PhD')], default='B.Tech', max_length=30),
        ),
    ]
