# Generated by Django 2.2.1 on 2021-11-09 07:20

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_auto_20211108_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=30)),
                ('vaccine_name', models.CharField(blank=True, max_length=15)),
                ('dose_taken', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2)], default='1', null=True)),
                ('date1', models.DateField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to=base.models.user_directory_path)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
