# Generated by Django 2.2.1 on 2021-11-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_vaccdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccdetails',
            name='vaccine_name',
            field=models.CharField(blank=True, choices=[('COVAXIN', 'Covaxin'), ('COVISHIELD', 'Covishield'), ('SPUTNIK', 'Sputnik')], max_length=15),
        ),
    ]
