# Generated by Django 2.2.1 on 2021-11-09 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_auto_20211109_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
