# Generated by Django 2.2.1 on 2021-11-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20211109_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True),
        ),
    ]
