# Generated by Django 2.2.1 on 2021-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211110_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccdetails',
            name='dose_taken',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True),
        ),
    ]
