# Generated by Django 2.2.1 on 2021-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20211110_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('ARCHITECTURE ENGINEERING', 'Architecture Engineering'), ('BIOCHEMICAL ENGINEERING', 'Biochemical Engineering'), ('CEREMIC ENGINEERING', 'Ceremic Engineering'), ('CHEMICAL ENGINEERING', 'Chemical Engineering'), ('CIVIL ENGINEERING', 'Civil Engineering'), ('COMPUTER SCIENCE AND ENGINEERING', 'Computer Science and Engineering'), ('ELECTRICAL ENGINEERING', 'Electrical Engineering'), ('ELECTRONICS ENGINEERING', 'Electronics Engineering'), ('ENGINEERING PHYSICS', 'Engineering Physics'), ('INDUSTRIAL CHEMISTRY ENGINEERING', 'Industry Chemistry Engineering'), ('MATERIAL SCIENCE AND ENGINEERING', 'Material Science and Engineering'), ('MATHEMATICS AND COMPUTING', 'Mathematics and Computing'), ('MECHANICAL ENGINEERING', 'Mechanical Engineering'), ('METALLURGY ENGINEERING', 'Metallurgy Engineering'), ('MINING ENGINEERING', 'Mining Engineering'), ('PHARMACEUTICAL ENGINEERING', 'Pharmaceutical Engineering')], max_length=50),
        ),
    ]
